on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Maven Clean and Package
      run: mvn clean package

    - name : SSH KEY permission
      run : |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name : Add SSH Key
      uses : webfactory/ssh-agent@v0.5.3
      with :
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name : Add known_hosts
      run : |
        echo "3.36.97.132 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGZFY4R3oBQp9/O62iqwR/T1zSj6i7QpIJxdRe5+Sev5" >> ~/.ssh/known_hosts

    - name: clean ROOT directory
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.36.97.132 << 'EOF'
        sudo rm -rf /home/ubuntu/shinhan_team2_chukahaeyo/apache-tomcat-9.0.89/webapps/ROOT
        sudo rm -rf /home/ubuntu/shinhan_team2_chukahaeyo/apache-tomcat-9.0.89/webapps/ROOT.war
        EOF

    - name: Upload WAR file
      run: |
        scp -i ~/.ssh/id_rsa target/chukahaeyo-1.0.0-BUILD-SNAPSHOT.war ubuntu@3.36.97.132:/home/ubuntu/shinhan_team2_chukahaeyo/apache-tomcat-9.0.89/webapps/ROOT.war

    - name: Restart Tomcat on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@3.36.97.132 << 'EOF'
        kill `pgrep -f chukahaeyo`
        /home/ubuntu/shinhan_team2_chukahaeyo/apache-tomcat-9.0.89/bin/startup.sh
        EOF
